# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(vetiver)
library(rapidoc)

# Packages needed to generate model predictions
if (FALSE) {
    library(dials)
    library(dplyr)
    library(LiblineaR)
    library(parsnip)
    library(purrr)
    library(recipes)
    library(rlang)
    library(rsample)
    library(tibble)
    library(tidyr)
    library(tune)
    library(vctrs)
    library(workflows)
    library(yardstick)
}
b <- board_rsconnect(server = "https://colorado.rstudio.com/rsc")
v <- vetiver_pin_read(b, "julia.silge/biv_svm", version = "49025")

#* @plumber
function(pr) {
    pr %>% vetiver_pr_predict(v, type = "class", debug = TRUE)
}
